/**
 * Gasworks project catalog for media-mill modals.
 * Fill every "TODO" (and empty credits) before treating a project as publish-ready.
 * Loaded as a classic script; also exposes window.GASWORKS_PROJECTS.
 */
(function (global) {
  "use strict";

  var projects = [
    {
      slug: "iseered",
      title: "I See Red",
      client: "TODO",
      year: "TODO",
      lane: "Narratives",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/iseered.mp4",
      posterSrc: "/media/mill/iseered-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "nordic",
      title: "USA Nordic",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/nordic.mp4",
      posterSrc: "/media/mill/nordic-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "brighton",
      title: "Brighton",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/brighton.mp4",
      posterSrc: "/media/mill/brighton-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "cars",
      title: "TODO",
      client: "TODO",
      year: "TODO",
      lane: "TODO",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/cars.mp4",
      posterSrc: "/media/mill/cars-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "whoop",
      title: "WHOOP",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/whoop.mp4",
      posterSrc: "/media/mill/whoop-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "kiltech",
      title: "Kiltech",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/kiltech.mp4",
      posterSrc: "/media/mill/kiltech-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "powmow",
      title: "Powder Mountain",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/powmow.mp4",
      posterSrc: "/media/mill/powmow-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "lincoln-spot",
      title: "Lincoln",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/lincoln-spot.mp4",
      posterSrc: "/media/mill/lincoln-spot-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "porsche",
      title: "Porsche",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/porsche.mp4",
      posterSrc: "/media/mill/porsche-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "amici",
      title: "Amici",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/amici.mp4",
      posterSrc: "/media/mill/amici-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "talking-head",
      title: "TODO",
      client: "TODO",
      year: "TODO",
      lane: "TODO",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/talking-head.mp4",
      posterSrc: "/media/mill/talking-head-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "shan",
      title: "SHAN",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/shan.mp4",
      posterSrc: "/media/mill/shan-poster.jpg",
      fullSrc: "",
      externalUrl: "https://open.spotify.com/track/3OFHRbJtAlhV1mBqCiNQeD"
    },
    {
      slug: "nathan",
      title: "Nathan",
      client: "TODO",
      year: "TODO",
      lane: "Spotlights",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/nathan.mp4",
      posterSrc: "/media/portfolio/spotlights/19.jpg",
      fullSrc: "/media/portfolio/spotlights/19.mp4",
      externalUrl: null
    },
    {
      slug: "mfm",
      title: "My Friend Mickey",
      client: "TODO",
      year: "TODO",
      lane: "Narratives",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "/media/mill/mfm.mp4",
      posterSrc: "/media/mill/mfm-poster.jpg",
      fullSrc: "",
      externalUrl: null
    },
    {
      slug: "tiwypsl",
      title: "TIWYPSL",
      client: "TODO",
      year: "TODO",
      lane: "Narratives",
      role: "TODO",
      agency: null,
      credits: [],
      summary: "TODO",
      loopSrc: "",
      posterSrc: "/media/portfolio/narratives/09.jpg",
      fullSrc: "",
      externalUrl: null
    }
  ];

  global.GASWORKS_PROJECTS = projects;
})(typeof window !== "undefined" ? window : globalThis);
